# fly.toml file generated for md-to-pdf on 2022-08-26T13:27:59+02:00

app = "md-to-pdf"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  in